yatube/about/urls.py
from django.urls import path
from . import views

app_name = 'about'

urlpatterns = [
    # url - статичных информационных страниц
    path(
        'author/',
        views.AboutAuthorPage.as_view(),
        name='author'),
    path(
        'tech/',
        views.AboutTechPage.as_view(),
        name='tech'),
]

yatube/posts/urls.py
from django.urls import path
from . import views


app_name = 'posts'


urlpatterns = [
    # url - общие
    path(
        '',
        views.index,
        name='index'
    ),
    # url - страницы про пользователей
    path(
        'profile/<str:username>/',
        views.profile,
        name='profile'
    ),
    path(
        'follow/',
        views.follow_index,
        name='follow_index'
    ),
    path(
        'profile/<str:username>/follow',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
    # url - страницы про группы
    path(
        'group/<slug:slug>/',
        views.group_posts,
        name='group_list'
    ),
    # url - страницы про посты
    path(
        'posts/<int:post_id>/edit/',
        views.post_edit,
        name='post_edit'
    ),
    path(
        'posts/<int:post_id>/',
        views.post_detail,
        name='post_detail'
    ),
    path(
        'create/',
        views.post_create,
        name='post_create'
    ),
    path(
        'posts/<int:post_id>/comment/',
        views.add_comment,
        name='add_comment'
    ),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static


handler404 = 'core.views.page_not_found'
handler403 = 'core.views.csrf_failure'
handler500 = 'core.views.internal_server_error'


urlpatterns = [
    # url - общие
    path(
        '',
        include('posts.urls', namespace='posts')
    ),
    path(
        'about/',
        include('about.urls', namespace='about')
    ),
    # url - страницы про пользователей
    path(
        'admin/',
        admin.site.urls
    ),
    path(
        'auth/',
        include('users.urls')
    ),
    path(
        'auth/',
        include('django.contrib.auth.urls')
    ),
]


if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()


class Post(models.Model):
    """Класс модели базы данных для хранения постовю"""
    text = models.TextField(
        verbose_name='Текст поста',
        help_text='Введите текст поста',
    )
    pub_date = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Дата пубикации'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='Автор'
    )
    group = models.ForeignKey(
        'Group',
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        related_name='posts',
        verbose_name='Группа',
        help_text='Группа, к которой будет относиться пост'
    )
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True
    )

    class Meta:
        ordering = ['-pub_date']
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'

    def __str__(self):
        return self.text[:15]


class Group(models.Model):
    """Класс модели базы данных для хранения групп."""
    title = models.CharField(
        verbose_name='Название группы',
        max_length=200
    )
    slug = models.SlugField(
        verbose_name='Адрес группы в url',
        unique=True
    )
    description = models.TextField(
        verbose_name='Описание группы'
    )

    def __str__(self):
        return self.title


class Comment(models.Model):
    """Класс модели базы данных для хранения комментариев
    пользователей."""
    post = models.ForeignKey(
        'Post',
        blank=True,
        null=True,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Пост',
        help_text='Комментарий оставлен этим пользователем Yatube'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Автор'
    )
    text = models.TextField(
        verbose_name='Текст комментария',
        help_text='Введите свое независимое мнение относительно '
                  'представленного контента',
    )
    created = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Дата пубикации'
    )

    class Meta:
        ordering = ['-created']
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'

    def __str__(self):
        return f'Комментарий: {self.text[:15]}'


class Follow(models.Model):
    """Класс модели базы данных для хранения подписок
    пользователей друг на друга."""

    author = models.ForeignKey(
        User,
        null=True,
        on_delete=models.CASCADE,
        related_name='following',
        verbose_name='Публикатор'
    )
    user = models.ForeignKey(
        User,
        null=True,
        on_delete=models.CASCADE,
        related_name='follower',
        verbose_name='Подписчик'
    )

    class Meta:
        verbose_name = 'Подписка'
        verbose_name_plural = 'Подписки'
        constraints = [
            models.UniqueConstraint(fields=['user', 'author'],
                                    name='unique_follow')
        ]

    def __str__(self):
        return f'Подписка {self.user} на {self.author}'

yatube/posts/forms.py
from django import forms
from . models import Post, Comment


class PostForm(forms.ModelForm):
    """Класс для формы создания нового поста."""
    class Meta:
        model = Post
        fields = ('text', 'group', 'image')


class CommentForm(forms.ModelForm):
    """Класс для формы создания нового комментария."""
    class Meta:
        model = Comment
        fields = ('text', )

yatube/posts/views.py
from django.contrib.auth.decorators import login_required
from django.views.decorators.cache import cache_page
from django.shortcuts import render, get_object_or_404, redirect
from .models import User, Post, Group, Follow
from .forms import PostForm, CommentForm
from .paginator import make_pagination


@login_required
def add_comment(request, post_id):
    """Для зарегистрированных пользователей открывает страницу
    с подробной информацией о посте, где можно оставить комментарий."""
    post = get_object_or_404(Post, pk=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


def group_posts(request, slug):
    """Возвращает заполненный шаблон страницы с информацией
    о постах группы slug."""

    group = get_object_or_404(Group, slug=slug)
    post_list = group.posts.select_related('author').all()
    page_obj = make_pagination(request, post_list)

    return render(
        request,
        'posts/group_list.html',
        {'group': group, 'page_obj': page_obj}
    )


@cache_page(20, key_prefix="index_page")
def index(request):
    """Возвращает заполненный шаблон страницы со всеми
    постами из БД."""

    post_list = Post.objects.select_related('group', 'author').all()
    page_obj = make_pagination(request, post_list)

    return render(
        request,
        'posts/index.html',
        {'page_obj': page_obj}
    )


@login_required
def post_create(request):
    """При получении POST-запроса сохраняет данные в БД
    и открывает стриницу профиля автора.
        При получении GET-запроса открывает пустую форму
    для создания нового поста."""
    form = PostForm(request.POST or None,
                    files=request.FILES or None)
    if request.method == 'POST':
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            return redirect('posts:profile', post.author)

    return render(
        request,
        'posts/create_post.html',
        {'form': form}
    )


def post_detail(request, post_id):
    """Возвращает заполненный шаблон с подробной
    информацией о посте post_id."""

    post_obj = get_object_or_404(Post, pk=post_id)
    posts_comment = post_obj.comments.filter(pk=post_id)
    comment_form = CommentForm(request.POST or None)

    return render(
        request,
        'posts/post_detail.html',
        {
            'post': post_obj,
            'comments': posts_comment,
            'form': comment_form,
        }
    )


@login_required
def post_edit(request, post_id):
    """Для автора поста post_id:
    При получении POST-запроса обновляет данные в БД
    и открывает стриницу с подробной информацией о посте post_id.
    При получении GET-запроса открывает форму, заполненную
    данными поста post_id.
        Для других пользователей:
    Перенаправляет на страницу с подробной информацией
    о посте post_id."""
    post_obj = get_object_or_404(Post, pk=post_id)
    if request.user != post_obj.author:
        return redirect('posts:post_detail', post_id)

    post_form = PostForm(
        request.POST or None,
        files=request.FILES or None,
        instance=post_obj
    )
    if request.method == 'POST':
        if post_form.is_valid():
            post_form.save()
            return redirect('posts:post_detail', post_id)

    return render(
        request,
        'posts/create_post.html',
        {
            'form': post_form,
            'is_edit': True,
            'post_id': post_id,
        }
    )


def profile(request, username):
    """Возвращает заполненный шаблон со всеми постами
    пользователя username - страницу профиля username."""

    author = get_object_or_404(User, username=username)
    post_list = author.posts.select_related('group').all()
    page_obj = make_pagination(request, post_list)

    following = (request.user.is_authenticated
                 and author.following.filter(user=request.user).exists()
                 )

    return render(
        request,
        'posts/profile.html',
        {
            'page_obj': page_obj,
            'author': author,
            'following': following,
        }
    )


@login_required
def follow_index(request):
    """Страница с постами авторов, на которых подписан пользователь."""
    post_list = Post.objects.filter(author__following__user=request.user)
    page_obj = make_pagination(request, post_list)

    return render(
        request,
        'posts/follow.html',
        {'page_obj': page_obj}
    )


@login_required
def profile_follow(request, username):
    """Подписка пользователя на публикации автора username."""
    author = get_object_or_404(User, username=username)

    if (
            Follow.objects.filter(author=author, user=request.user).exists()
            or request.user == author
    ):
        return redirect('posts:profile', username=username)

    Follow.objects.create(author=author,
                          user=request.user)

    return redirect('posts:profile', username=username)


@login_required
def profile_unfollow(request, username):
    """Отписка пользователя от публикаций автора username."""
    author = get_object_or_404(User, username=username)
    follow_obj = Follow.objects.filter(author=author,
                                       user=request.user)
    if follow_obj.exists():
        follow_obj.delete()

    return redirect('posts:profile', username=username)

yatube/templates/posts/create_post.html
{% extends 'base.html' %}
{% load static %}
{% block service_content %}
  <title>
    {% if is_edit %}
      Редактирование поста
    {% else %}
      Новый пост
    {% endif %}
  </title>
{% endblock %}
{% block content %}
  <div class="container py-5">
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">
            {% if is_edit %}
              Редактировать запись
            {% else %}
              Добавить запись
            {% endif %}
          </div>
          <div class="card-body">
            {% load user_filters %}
            {% include 'includes/check_form_error.html' %}
              {% if is_edit %}
                <form method="post" action="{% url 'posts:post_edit' post_id %}" enctype="multipart/form-data">
              {% else %}
                <form method="post" action="{% url 'posts:post_create' %}" enctype="multipart/form-data">
              {% endif %}
                {% csrf_token %}
                {% include 'includes/post_form.html' %}
                <div class="d-flex justify-content-end">
                  <button type="submit" class="btn btn-primary">
                    {% if is_edit %}
                      Сохранить
                    {% else %}
                      Добавить
                    {% endif %}
                  </button>
                </div>
              </form>
          </div> <!-- card body -->
        </div> <!-- card -->
      </div> <!-- col -->
    </div> <!-- row -->
  </div> <!-- container -->
{% endblock %}

yatube/templates/posts/follow.html
{% extends 'base.html' %}
{% load static %}
{% block service_content %}
  <title>
    Последние обновления читаемых авторов
  </title>
{% endblock %}
{% block content %}
  <div class="container py-5">
    {% include 'posts/includes/switcher.html' %}
    {% for post in page_obj %}
      {% include 'posts/includes/single_post.html' %}
      {% if post.group %}
        <a href="{% url 'posts:group_list' post.group.slug %}"> все записи группы</a>
      {% endif %}
      {% if not forloop.last %}
        <hr>
      {% endif %}
    {% endfor %}
    {% include 'posts/includes/paginator.html' %}
  </div>
{% endblock %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% load static %}
{% block service_content %}
  <title>
    Записи сообщества {{ group.title }}
  </title>
{% endblock %}
{% block content %}
  <div class="container py-5">
    <h1>
      {{ group.title }}
    </h1>
    <p>
      {{ group.description }}
    </p>
    {% for post in page_obj %}
      {% include 'posts/includes/single_post.html' %}
      {% if not forloop.last %}
        <hr>
      {% endif %}
    {% endfor %}
    {% include 'posts/includes/paginator.html' %}
  </div>
{% endblock %}

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% load static %}
{% block service_content %}
  <title>
    Последние обновления на сайте
  </title>
{% endblock %}
{% block content %}
  <div class="container py-5">
    {% include 'posts/includes/switcher.html' %}
    {% for post in page_obj %}
      {% include 'posts/includes/single_post.html' %}
      {% if post.group %}
        <a href="{% url 'posts:group_list' post.group.slug %}"> все записи группы</a>
      {% endif %}
      {% if not forloop.last %}
        <hr>
      {% endif %}
    {% endfor %}
    {% include 'posts/includes/paginator.html' %}
  </div>
{% endblock %}

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% load static %}
{% load thumbnail %}
{% block service_content %}
    <title>
      Пост {{ post.text|slice:"0:30" }}
    </title>
{% endblock %}
{% block content %}
  <main>
    <div class="container py-5">
      <div class="row">
        <aside class="col-12 col-md-3">
          <ul class="list-group list-group-flush">
            <li class="list-group-item">
              Дата публикации: {{ post.pub_date|date:"d E Y" }}
            </li>
            {% if post.group %}
              <li class="list-group-item">
                Группа: {{ post.group.slug }}
                <a href="{% url 'posts:group_list' post.group.slug %}">
                  все записи группы
                </a>
              </li>
            {% endif %}
            <li class="list-group-item">
              Автор: {{ post.author.get_full_name }} {{ post.author.username }}
            </li>
            <li class="list-group-item d-flex justify-content-between align-items-center">
              Всего постов автора:  <span >{{ post.author.posts.count }}</span>
            </li>
            <li class="list-group-item">
              <a href="{% url 'posts:profile' post.author.username %}">
                все посты пользователя
              </a>
            </li>
          </ul>
        </aside>
        <article class="col-12 col-md-9">
          {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
            <img class="card-img my-2" src="{{ im.url }}">
          {% endthumbnail %}
          <p>
           {{ post.text }}
          </p>
          {% include 'posts/includes/comments_list.html' %}
          {% if request.user == post.author%}
            <a class="btn btn-primary" href="{% url 'posts:post_edit' post.id %}">
              редактировать запись
            </a>
          {% endif %}
        </article>
      </div>
    </div>
  </main>
{% endblock %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% load static %}
{% block service_content %}
  <title>
    Профайл пользователя {{ author }}
  </title>
{% endblock %}
{% block content %}
  <main>
    <div class="container py-5">
      <div class="mb-5">
        <h1>Все посты пользователя {{ author }} </h1>
        <h3>Всего постов: {{ author.posts.count }} </h3>
        {% if author.username != request.user %}
          {% if following %}
            <a
              class="btn btn-lg btn-light"
              href="{% url 'posts:profile_unfollow' author.username %}" role="button"
            >
              Отписаться
            </a>
          {% else %}
            <a
              class="btn btn-lg btn-primary"
              href="{% url 'posts:profile_follow' author.username %}" role="button"
            >
              Подписаться
            </a>
          {% endif %}
        {% endif %}

      </div>
        {% for post in page_obj %}
          {% include 'posts/includes/single_post.html' %}
          {% if post.group %}
            <a href="{% url 'posts:group_list' post.group.slug %}"> все записи группы</a>
          {% endif %}
          {% if not forloop.last %}
            <hr>
          {% endif %}
        {% endfor %}
      {% include 'posts/includes/paginator.html' %}
    </div>
  </main>
{% endblock %}