yatube/about/urls.py
from django.urls import path
from . import views

app_name = 'about'

urlpatterns = [
    # url - статичных информационных страниц
    path(
        'author/',
        views.AboutAuthorPage.as_view(),
        name='author'),
    path(
        'tech/',
        views.AboutTechPage.as_view(),
        name='tech'),
]

yatube/users/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView, LoginView, \
    PasswordResetView, PasswordChangeView
from . import views


app_name = 'users'


urlpatterns = [
    # url - страницы для действий с авторизацией пользователя
    path(
        'logout/',
        LogoutView.as_view(template_name='users/logged_out.html'),
        name='logout'
    ),
    path(
        'login/',
        LoginView.as_view(template_name='users/login.html'),
        name='login'
    ),
    path(
        'signup/',
        views.SignUp.as_view(),
        name='signup'
    ),
    # url - страницы для операций с паролем
    path(
        'password_reset_form/',
        PasswordResetView.as_view(),
        name='password_reset_form'
    ),
    path(
        'password_change/',
        PasswordChangeView.as_view(),
        name='password_change'
    ),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static


handler404 = 'core.views.page_not_found'
handler403 = 'core.views.csrf_failure'
handler500 = 'core.views.internal_server_error'


urlpatterns = [
    # url - общие
    path(
        '',
        include('posts.urls', namespace='posts')
    ),
    path(
        'about/',
        include('about.urls', namespace='about')
    ),
    # url - страницы про пользователей
    path(
        'admin/',
        admin.site.urls
    ),
    path(
        'auth/',
        include('users.urls')
    ),
    path(
        'auth/',
        include('django.contrib.auth.urls')
    ),
]


if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/users/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model


User = get_user_model()


class CreationForm(UserCreationForm):
    """Класс для формы регистрации нового пользователя."""
    class Meta(UserCreationForm.Meta):
        model = User
        fields = ('first_name', 'last_name', 'username', 'email')

yatube/users/views.py
from django.views.generic import CreateView
from django.urls import reverse_lazy

from .forms import CreationForm


class SignUp(CreateView):
    """Класс для формирования шаблона с формой регистрации нового
    пользователя. После успешной регистрации перенаправляет
    на главную страницу проекта."""

    form_class = CreationForm
    success_url = reverse_lazy('posts:index')
    template_name = 'users/signup.html'

yatube/templates/users/logged_out.html
{% extends 'base.html' %}
{% block service_content %}
  <title>
    Вы вышли из системы
  </title>
{% endblock %}
{% block content %}
<div class="row justify-content-center">
  <div class="col-md-8 p-5">
    <div class="card">
      <div class="card-header">
        Выход
      </div>
      <div class="card-body">
        <p>
          Вы вышли из своей учётной записи. Ждём вас снова!
        </p>
      </div> <!-- card body -->
    </div> <!-- card -->
  </div> <!-- col -->
</div> <!-- row -->
{% endblock %} 

yatube/templates/users/login.html
{% extends "base.html" %}
{% block service_content %}
  <title>Войти </title>
{% endblock %}
{% block content %}
{% load user_filters %}
  <div class="container py-5">
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">
            Войти на сайт
          </div>
          <div class="card-body">
            {% include 'includes/check_form_error.html' %}
            <form method="post">
              {% csrf_token %}
              {% include 'includes/post_form.html' %}
              <div class="col-md-6 offset-md-4">
                <button type="submit" class="btn btn-primary">
                  Войти
                </button>
                <a href="{% url 'users:password_reset_form' %}" class="btn btn-link">
                  Забыли пароль?
                </a>
              </div>
            </form>
          </div> <!-- card body -->
        </div> <!-- card -->
      </div> <!-- col -->
    </div> <!-- row -->
  </div>
{% endblock %}

yatube/templates/users/signup.html
{% extends "base.html" %}
{% block service_content %}
  <title>Зарегистрироваться </title>
{% endblock %}
{% block content %}
  <div class="container py-5">
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">Зарегистрироваться</div>
            <div class="card-body">
            {% load user_filters %}
            {% include 'includes/check_form_error.html' %}

            <form method="post" action="{% url 'users:signup' %}">
            {% csrf_token %}
            {% include 'includes/post_form.html' %}
            <div class="col-md-6 offset-md-4">
              <button type="submit" class="btn btn-primary">
                Зарегистрироваться
              </button>
            </div>
            </form>
            </div> <!-- card body -->
          </div> <!-- card -->
        </div> <!-- col -->
    </div> <!-- row -->
  </div>
{% endblock %}